---
- name: Restart W32tm
  ansible.windows.win_service:
    name: w32tm
    state: restarted
  listen: restart ntp

- name: Restart DNS Client
  ansible.windows.win_service:
    name: dnscache
    state: restarted
  listen: restart dns client

- name: Restart WinRM
  ansible.windows.win_service:
    name: WinRM
    state: restarted
  listen: restart winrm
