---
- name: Restart Elasticsearch
  ansible.builtin.systemd:
    name: elasticsearch
    state: restarted
  listen: restart elasticsearch

- name: Restart Logstash
  ansible.builtin.systemd:
    name: logstash
    state: restarted
  listen: restart logstash

- name: Restart Kibana
  ansible.builtin.systemd:
    name: kibana
    state: restarted
  listen: restart kibana
