# Generated by Django 5.2.12 on 2026-03-29 22:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Deployment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "phase",
                    models.CharField(
                        choices=[
                            ("pre_flight", "Pre-Flight"),
                            ("discovery", "Discovery"),
                            ("topology", "Topology"),
                            ("cabling_validation", "Cabling Validation"),
                            ("heavy_transfers", "Heavy Transfers"),
                            ("network_config", "Network Configuration"),
                            ("laptop_pivot", "Laptop Pivot"),
                            ("server_provision", "Server Provisioning"),
                            ("post_install", "Post-Install"),
                            ("final_validation", "Final Validation"),
                            ("complete", "Complete"),
                            ("failed", "Failed"),
                        ],
                        default="pre_flight",
                        max_length=30,
                    ),
                ),
                ("bootstrap_subnet", models.CharField(blank=True, max_length=50)),
                ("laptop_ip", models.CharField(blank=True, max_length=50)),
                ("management_vlan", models.IntegerField(default=0)),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-started_at"],
            },
        ),
        migrations.CreateModel(
            name="DeploymentLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("INFO", "Info"),
                            ("WARNING", "Warning"),
                            ("ERROR", "Error"),
                        ],
                        default="INFO",
                        max_length=10,
                    ),
                ),
                ("phase", models.CharField(blank=True, max_length=30)),
                ("message", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "deployment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="logs",
                        to="dashboard.deployment",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Device",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ip", models.GenericIPAddressField()),
                ("mac", models.CharField(blank=True, max_length=17)),
                ("serial", models.CharField(blank=True, max_length=100)),
                (
                    "platform",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("cisco_ios", "Cisco IOS"),
                            ("cisco_iosxe", "Cisco IOS-XE"),
                            ("cisco_asa", "Cisco ASA"),
                            ("cisco_ftd", "Cisco FTD"),
                            ("hpe_dl325_gen10", "HPE DL325 Gen10"),
                        ],
                        max_length=30,
                    ),
                ),
                ("hostname", models.CharField(blank=True, max_length=200)),
                ("intended_hostname", models.CharField(blank=True, max_length=200)),
                (
                    "role",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("core-switch", "Core Switch"),
                            ("access-switch", "Access Switch"),
                            ("distribution-switch", "Distribution Switch"),
                            ("border-router", "Border Router"),
                            ("perimeter-firewall", "Perimeter Firewall"),
                            ("compute-node", "Compute Node"),
                            ("management-server", "Management Server"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("unknown", "Unknown"),
                            ("discovered", "Discovered"),
                            ("identified", "Identified"),
                            ("validated", "Validated"),
                            ("configuring", "Configuring"),
                            ("configured", "Configured"),
                            ("provisioning", "Provisioning"),
                            ("provisioned", "Provisioned"),
                            ("failed", "Failed"),
                        ],
                        default="unknown",
                        max_length=20,
                    ),
                ),
                ("bfs_depth", models.IntegerField(blank=True, null=True)),
                ("config_order", models.IntegerField(blank=True, null=True)),
                ("management_ip", models.CharField(blank=True, max_length=50)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deployment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="devices",
                        to="dashboard.deployment",
                    ),
                ),
            ],
            options={
                "ordering": ["config_order", "intended_hostname"],
            },
        ),
        migrations.CreateModel(
            name="CablingResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("local_port", models.CharField(max_length=100)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("correct", "Correct"),
                            ("wrong_device", "Wrong Device"),
                            ("wrong_port", "Wrong Port"),
                            ("missing", "Missing"),
                            ("unexpected", "Unexpected"),
                            ("adaptable", "Adaptable"),
                        ],
                        max_length=20,
                    ),
                ),
                ("actual_remote", models.CharField(blank=True, max_length=200)),
                ("actual_remote_port", models.CharField(blank=True, max_length=100)),
                ("intended_remote", models.CharField(blank=True, max_length=200)),
                ("intended_remote_port", models.CharField(blank=True, max_length=100)),
                ("message", models.TextField(blank=True)),
                (
                    "device",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cabling_results",
                        to="dashboard.device",
                    ),
                ),
            ],
            options={
                "ordering": ["local_port"],
            },
        ),
    ]
