# Generated by Django 5.2.12 on 2026-03-29 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="deployment",
            name="phase",
            field=models.CharField(
                choices=[
                    ("pre_flight", "Pre-Flight"),
                    ("discovery", "Discovery"),
                    ("topology", "Topology"),
                    ("cabling_validation", "Cabling Validation"),
                    ("firmware_upgrade", "Firmware Upgrade"),
                    ("heavy_transfers", "Heavy Transfers"),
                    ("network_config", "Network Configuration"),
                    ("laptop_pivot", "Laptop Pivot"),
                    ("server_provision", "Server Provisioning"),
                    ("ntp_provision", "NTP Provisioning"),
                    ("post_install", "Post-Install"),
                    ("final_validation", "Final Validation"),
                    ("complete", "Complete"),
                    ("failed", "Failed"),
                ],
                default="pre_flight",
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="device",
            name="platform",
            field=models.CharField(
                blank=True,
                choices=[
                    ("cisco_ios", "Cisco IOS"),
                    ("cisco_iosxe", "Cisco IOS-XE"),
                    ("cisco_asa", "Cisco ASA"),
                    ("cisco_ftd", "Cisco FTD"),
                    ("hpe_dl325_gen10", "HPE DL325 Gen10"),
                    ("hpe_dl360_gen10", "HPE DL360 Gen10"),
                    ("hpe_dl380_gen10", "HPE DL380 Gen10"),
                    ("meinberg_lantime", "Meinberg LANTIME"),
                ],
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="device",
            name="role",
            field=models.CharField(
                blank=True,
                choices=[
                    ("core-switch", "Core Switch"),
                    ("access-switch", "Access Switch"),
                    ("distribution-switch", "Distribution Switch"),
                    ("border-router", "Border Router"),
                    ("perimeter-firewall", "Perimeter Firewall"),
                    ("compute-node", "Compute Node"),
                    ("management-server", "Management Server"),
                    ("ntp-server", "NTP Server"),
                ],
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="device",
            name="state",
            field=models.CharField(
                choices=[
                    ("unknown", "Unknown"),
                    ("discovered", "Discovered"),
                    ("identified", "Identified"),
                    ("validated", "Validated"),
                    ("firmware_upgrading", "Firmware Upgrading"),
                    ("firmware_upgraded", "Firmware Upgraded"),
                    ("configuring", "Configuring"),
                    ("configured", "Configured"),
                    ("bios_configuring", "BIOS Configuring"),
                    ("bios_configured", "BIOS Configured"),
                    ("raid_configuring", "RAID Configuring"),
                    ("raid_configured", "RAID Configured"),
                    ("spp_installing", "SPP Installing"),
                    ("spp_installed", "SPP Installed"),
                    ("os_installing", "OS Installing"),
                    ("os_installed", "OS Installed"),
                    ("ilo_configuring", "iLO Configuring"),
                    ("ilo_configured", "iLO Configured"),
                    ("provisioning", "Provisioning"),
                    ("provisioned", "Provisioned"),
                    ("failed", "Failed"),
                ],
                default="unknown",
                max_length=20,
            ),
        ),
    ]
