# Generated by Django 6.0.3 on 2026-03-30 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_alter_deployment_phase_alter_device_platform_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deployment',
            name='phase',
            field=models.CharField(choices=[('pre_flight', 'Pre-Flight'), ('discovery', 'Discovery'), ('topology', 'Topology'), ('cabling_validation', 'Cabling Validation'), ('firmware_upgrade', 'Firmware Upgrade'), ('heavy_transfers', 'Heavy Transfers'), ('network_config', 'Network Configuration'), ('laptop_pivot', 'Laptop Pivot'), ('server_provision', 'Server Provisioning'), ('ntp_provision', 'NTP Provisioning'), ('post_install', 'Post-Install'), ('final_validation', 'Final Validation'), ('complete', 'Complete'), ('failed', 'Failed'), ('stopped', 'Stopped')], default='pre_flight', max_length=30),
        ),
        migrations.AlterField(
            model_name='device',
            name='state',
            field=models.CharField(choices=[('unknown', 'Unknown'), ('discovered', 'Discovered'), ('identified', 'Identified'), ('validated', 'Validated'), ('firmware_upgrading', 'Firmware Upgrading'), ('firmware_upgraded', 'Firmware Upgraded'), ('configuring', 'Configuring'), ('configured', 'Configured'), ('bios_configuring', 'BIOS Configuring'), ('bios_configured', 'BIOS Configured'), ('raid_configuring', 'RAID Configuring'), ('raid_configured', 'RAID Configured'), ('spp_installing', 'SPP Installing'), ('spp_installed', 'SPP Installed'), ('os_installing', 'OS Installing'), ('os_installed', 'OS Installed'), ('os_configuring', 'OS Configuring'), ('os_configured', 'OS Configured'), ('ilo_configuring', 'iLO Configuring'), ('ilo_configured', 'iLO Configured'), ('provisioning', 'Provisioning'), ('provisioned', 'Provisioned'), ('failed', 'Failed')], default='unknown', max_length=20),
        ),
    ]
