# Generated by Django 5.x (Sprint 5 — dashboard consolidation)
# Adds new fields to Deployment and new models merged from the legacy dashboard app.

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0004_alter_deployment_phase_alter_device_state"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # ── Deployment: new fields ─────────────────────────────────────────
        migrations.AddField(
            model_name="deployment",
            name="site_name",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="deployment",
            name="site_slug",
            field=models.SlugField(blank=True),
        ),
        migrations.AddField(
            model_name="deployment",
            name="template_name",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="deployment",
            name="template_version",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="deployment",
            name="bundle_path",
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name="deployment",
            name="manifest_hash",
            field=models.CharField(
                blank=True,
                max_length=64,
                help_text="SHA-256 of manifest.yaml",
            ),
        ),
        migrations.AddField(
            model_name="deployment",
            name="site_config",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="JSON configuration for vCenter/NSX deployment phases",
            ),
        ),
        migrations.AddField(
            model_name="deployment",
            name="operator",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="deployments",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        # ── DeploymentPhase ────────────────────────────────────────────────
        migrations.CreateModel(
            name="DeploymentPhase",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("phase_number", models.IntegerField()),
                ("phase_name", models.CharField(max_length=100)),
                ("status", models.CharField(
                    choices=[
                        ("pending", "Pending"), ("running", "Running"),
                        ("completed", "Completed"), ("warning", "Warning"),
                        ("failed", "Failed"), ("skipped", "Skipped"),
                    ],
                    db_index=True, default="pending", max_length=20,
                )),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("duration_seconds", models.FloatField(blank=True, null=True)),
                ("warning_count", models.IntegerField(default=0)),
                ("error_message", models.TextField(blank=True)),
                ("deployment", models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name="phases",
                    to="dashboard.deployment",
                )),
            ],
            options={"ordering": ["phase_number"]},
        ),
        migrations.AddConstraint(
            model_name="deploymentphase",
            constraint=models.UniqueConstraint(
                fields=["deployment", "phase_number"],
                name="unique_deployment_phase_number",
            ),
        ),
        # ── FactoryReset ───────────────────────────────────────────────────
        migrations.CreateModel(
            name="FactoryReset",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("status", models.CharField(
                    choices=[
                        ("running", "Running"), ("completed", "Completed"),
                        ("failed", "Failed"), ("aborted", "Aborted"),
                    ],
                    db_index=True, default="running", max_length=20,
                )),
                ("sanitisation_method", models.CharField(default="write-erase", max_length=100)),
                ("report", models.JSONField(blank=True, default=dict)),
                ("deployment", models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name="factory_resets",
                    to="dashboard.deployment",
                )),
                ("operator", models.ForeignKey(
                    blank=True,
                    null=True,
                    on_delete=django.db.models.deletion.SET_NULL,
                    related_name="factory_resets",
                    to=settings.AUTH_USER_MODEL,
                )),
            ],
            options={"ordering": ["-started_at"]},
        ),
        # ── ResetPhase ─────────────────────────────────────────────────────
        migrations.CreateModel(
            name="ResetPhase",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("phase_number", models.IntegerField()),
                ("phase_name", models.CharField(max_length=100)),
                ("status", models.CharField(
                    choices=[
                        ("pending", "Pending"), ("running", "Running"),
                        ("completed", "Completed"), ("warning", "Warning"),
                        ("failed", "Failed"), ("skipped", "Skipped"),
                    ],
                    default="pending", max_length=20,
                )),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("devices_reset", models.IntegerField(default=0)),
                ("devices_total", models.IntegerField(default=0)),
                ("log_output", models.TextField(blank=True)),
                ("reset", models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name="phases",
                    to="dashboard.factoryreset",
                )),
            ],
            options={"ordering": ["phase_number"]},
        ),
        migrations.AddConstraint(
            model_name="resetphase",
            constraint=models.UniqueConstraint(
                fields=["reset", "phase_number"],
                name="unique_reset_phase_number",
            ),
        ),
        # ── DeviceResetCertificate ─────────────────────────────────────────
        migrations.CreateModel(
            name="DeviceResetCertificate",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("serial_number", models.CharField(max_length=100)),
                ("sanitisation_method", models.CharField(max_length=100)),
                ("verified", models.BooleanField(default=False)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("certificate_id", models.CharField(
                    blank=True, max_length=36,
                    help_text="UUID from SanitisationCertificate",
                )),
                ("checksum", models.CharField(
                    blank=True, max_length=64,
                    help_text="SHA-256 of certificate payload",
                )),
                ("notes", models.TextField(blank=True)),
                ("device", models.ForeignKey(
                    blank=True,
                    null=True,
                    on_delete=django.db.models.deletion.SET_NULL,
                    related_name="reset_certificates",
                    to="dashboard.device",
                )),
                ("operator", models.ForeignKey(
                    blank=True,
                    null=True,
                    on_delete=django.db.models.deletion.SET_NULL,
                    related_name="issued_certificates",
                    to=settings.AUTH_USER_MODEL,
                )),
                ("reset", models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name="certificates",
                    to="dashboard.factoryreset",
                )),
            ],
            options={"ordering": ["-timestamp"]},
        ),
        # ── Fleet: SiteRecord ──────────────────────────────────────────────
        migrations.CreateModel(
            name="SiteRecord",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("site_name", models.CharField(max_length=200)),
                ("site_slug", models.SlugField(unique=True)),
                ("location", models.CharField(blank=True, max_length=200)),
                ("contact", models.EmailField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("last_deployment", models.ForeignKey(
                    blank=True,
                    null=True,
                    on_delete=django.db.models.deletion.SET_NULL,
                    related_name="fleet_site",
                    to="dashboard.deployment",
                )),
            ],
            options={"ordering": ["site_name"]},
        ),
        # ── Fleet: TemplateRecord ──────────────────────────────────────────
        migrations.CreateModel(
            name="TemplateRecord",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=200)),
                ("current_version", models.CharField(max_length=50)),
                ("previous_versions", models.JSONField(blank=True, default=list)),
                ("changelog", models.TextField(blank=True)),
                ("released_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={"ordering": ["name"]},
        ),
        migrations.AddConstraint(
            model_name="templaterecord",
            constraint=models.UniqueConstraint(
                fields=["name", "current_version"],
                name="unique_template_version",
            ),
        ),
        # ── Fleet: FleetScan ───────────────────────────────────────────────
        migrations.CreateModel(
            name="FleetScan",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("scanned_at", models.DateTimeField(auto_now_add=True)),
                ("site_count", models.IntegerField(default=0)),
                ("compliant_count", models.IntegerField(default=0)),
                ("outdated_count", models.IntegerField(default=0)),
                ("unknown_count", models.IntegerField(default=0)),
                ("scan_report", models.JSONField(blank=True, default=dict)),
            ],
            options={"ordering": ["-scanned_at"]},
        ),
        # ── Fleet: SiteComplianceRecord ────────────────────────────────────
        migrations.CreateModel(
            name="SiteComplianceRecord",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("template_name", models.CharField(max_length=200)),
                ("deployed_version", models.CharField(blank=True, max_length=50)),
                ("current_version", models.CharField(blank=True, max_length=50)),
                ("status", models.CharField(
                    choices=[
                        ("compliant", "Compliant"), ("outdated", "Outdated"),
                        ("unknown", "Unknown"), ("never_deployed", "Never Deployed"),
                    ],
                    db_index=True, default="unknown", max_length=20,
                )),
                ("deployed_at", models.DateTimeField(blank=True, null=True)),
                ("drift_details", models.JSONField(blank=True, default=dict)),
                ("scan", models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name="site_results",
                    to="dashboard.fleetscan",
                )),
                ("site", models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name="compliance_records",
                    to="dashboard.siterecord",
                )),
            ],
            options={"ordering": ["site__site_name"]},
        ),
        migrations.AddConstraint(
            model_name="sitecompliancerecord",
            constraint=models.UniqueConstraint(
                fields=["scan", "site"],
                name="unique_scan_site",
            ),
        ),
    ]
